apiVersion: apps/v1
kind: Deployment
metadata:
  name: so-be
  labels:
    app: so-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: so-be
  template:
    metadata:
      labels:
        app: so-be
    spec:
      containers:
        - name: so-be
          image: service-owl:5000/service-owl-be:latest
          imagePullPolicy: Always
          ports:
            - name: http-port
              containerPort: 8002
