apiVersion: v1
kind: Service
metadata:
  name: service-owl-be
  labels:
    name: service-owl-be
spec:
  ports:
    - name: http-port
      port: 8002
      targetPort: http-port
      protocol: TCP
      nodePort: 30802
    - name: ssh-port
      port: 8888
      targetPort: ssh-port
      protocol: TCP
      nodePort: 30888
  externalIPs:
    - 192.168.120.135
  selector:
    app: so-be
  type: NodePort
