apiVersion: v1
kind: Service
metadata:
  name: service-owl-be
  labels:
    name: service-owl-be
spec:
  ports:
    - port: 8002
      targetPort: http-port
      protocol: TCP
      nodePort: 30802
  externalIPs:
    - 192.168.120.135
  selector:
    app: so-be
  type: NodePort
